# Generated by Django 3.2.12 on 2022-04-05 18:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('preco', models.PositiveIntegerField(default=999999)),
                ('estoque', models.PositiveIntegerField(default=0)),
                ('imagem', models.CharField(max_length=200)),
                ('idproduto', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Venda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('cpf', models.CharField(max_length=11)),
                ('email', models.CharField(max_length=200)),
                ('endereco', models.CharField(max_length=200)),
                ('data', models.DateTimeField(default=django.utils.timezone.now)),
                ('idproduto', models.PositiveIntegerField(default=0)),
                ('quantidade', models.PositiveIntegerField(default=0)),
                ('valortotal', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
